apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
type: Opaque
stringData:
  JWT_KEY: mysecret
---
apiVersion: v1
kind: Secret
metadata:
  name: stripe-secret
type: Opaque
stringData:
  STRIPE_KEY: sk_test_51JwM0PJms7fa5vjxZumt5STMLfMkjKd4kShkQGMqkLOyUQBSbIC9NRxXaabf2QtXQ1BNZ32XYofynqi0kbNAsLSs00CQ0yR1R9
